# todo: this should just be owner_group/tenant
default_owner_group: root
workspace: gyrus

storage:
  provider: localfs
  root: ./.gyrus

index:
  provider: sqlite
  dsn: ./.gyrus/index.db

graph:
  provider: sqlite

search:
  provider: sqlite_fts5

ui:
  client: antigravity
